apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    # ReadWriteOnce: 한 노드에서만 접근 가능
    # ReadOnlyMany: 여러 노드에서 읽기 전용으로 접근 가능
    # ReadWriteMany: 여러 노드에서 접근 가능 (NFS)
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: "/mnt/data"